### ISSUE TITLE
Firebase Auth

### ISSUE THREAD

**Issue by victordeassis** [CocoaheadsBH/talks#11]
# Título da talk
Login Mágico com Firebase Auth

# Descrição da talk
Nesta talk tenho a intenção de mostrar as ferramentas de autenticação do Firebase.

# Data
27 de março

# Dados do Apresentador
Victor Alves Perdigão de Assis
victoralvespda@gmail.com
twitter.com/victoralvespda
https://www.facebook.com/VictorAlvespda
https://www.linkedin.com/in/victor-de-assis-b9120952/

**Comment by gabrieloliva** [comment]
@victordeassis Sua talk pode ser apresentada no CocoaHeads desse mês, né? Vai ser no dia 27.

**Comment by victordeassis** [comment]
Yes! Confirmado nesse mês!

**Comment by gabrieloliva** [comment]
Fechado!

**Comment by gabrieloliva** [comment]
@victordeassis evento marcado! https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/248980953/

**Comment by gabrieloliva** [comment]
@victordeassis assim que der faz um PR com os slides da sua talk atualizando o `past-talks.md` 😄

**Comment by gabrieloliva** [comment]
Muito obrigado pela talk e pela disponibilização dos slides, @victordeassis!
