### ISSUE TITLE
Programação orientada a Protocolos no Swift

### ISSUE THREAD

**Issue by paulogama** [CocoaheadsBH/talks#12]
# Título da talk
Programação orientada a Protocolos no Swift

# Descrição da talk
Protocol Oriented Programming in Swift
SOLID principles

# Data
27/03/2018

# Dados do Apresentador
Lilian Dias / Paulo Gama

**Comment by gabrieloliva** [comment]
@paulogama evento marcado: https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/248980953/

**Comment by gabrieloliva** [comment]
Muito obrigado pela talk e pelo PR incluindo os slides, @paulogama! 🎉

**Comment by paulogama** [comment]
Valeu \\o
