### ISSUE TITLE
UX for Dummies

### ISSUE THREAD

**Issue by GuilhermeCoelhoZup** [CocoaheadsBH/talks#15]
# Título da talk
UX for Dummies

# Descrição da talk
Vamos conversar um pouco sobre as origens de UX e como podemos aplicar algumas heurísticas no dia-a-dia de um desenvolvedor mobile.

# Data
03 de maio, no próximo CocoaHeadsBH!!!

# Dados do Apresentador
Nome: Guilherme Maciel de Aguiar Nunes Coelho // Wendersom Enock
Onde trabalha: ZUP Innovation
Email: guilherme.coelho@zup.com.br
Username no iOSDevBR: guicoelho
Redes sociais:

**Comment by gabrieloliva** [comment]
Olá @GuilhermeCoelhoZup! Muito obrigado pela proposta de talk! 👍 
A data da sua apresentação vai ser no dia 03 de maio, pode alterar na descrição por gentileza?

E uma dúvida... ta planejando quanto tempo pra essa talk mais ou menos?

Abraços! 👊

**Comment by GuilhermeCoelhoZup** [comment]
Cara ainda estamos montando(eu e Enock) a Talk e assim que tiver mais ou menos pronto eu te falo a duração pode ser?

**Comment by gabrieloliva** [comment]
@GuilhermeCoelhoZup evento agendado no meetup https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/250073212/

Ajude na divulgação! Abraços e até o dia 03! 😀

**Comment by gabrieloliva** [comment]
@GuilhermeCoelhoZup muito obrigado pela talk! Você poderia fazer um Pull Request adicionando seus slides e qualquer outras referencias no nosso arquivo `past-talks.md`?
