### ISSUE TITLE
Sorcery with Sourcery

### ISSUE THREAD

**Issue by marciliojrs** [CocoaheadsBH/talks#16]
# Título da talk
Sorcery with Sourcery - Metaprogramação com Swift 

# Descrição da talk
Constantemente gastamos muito tempo do nosso dia a dia repetindo tarefas que não requerem nenhum esforço mental, basicamente escrevendo códigos praticamente repetidos que só necessitam de alguns parâmetros diferentes. Iremos ver como usar metaprogramação para evitar essas repetições e assim podermos nos dedicar ao que realmente importa para os produtos em que trabalhamos.

# Data
03/05/2018

# Dados do Apresentador
Nome: Marcilio Júnior
Onde trabalha: Ignus Digital
Email: marciliojrs@gmail.com
Username no iOSDevBR: marcilio
Redes sociais: marciliojrs

**Comment by gabrieloliva** [comment]
@marciliojrs evento agendado no meetup https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/250073212/

Ajude na divulgação! Abraços e até o dia 03! 😀
