### ISSUE TITLE
Testes instrumentados com KIF

### ISSUE THREAD

**Issue by joaopedrok** [CocoaheadsBH/talks#17]
# Título da talk
Testes Instrumentados com o KIF

# Descrição da talk
Será uma breve apresentação sobre o que são testes instrumentados, pirâmide de testes, como definimos os testes junto com o QA, pequeno projeto com algumas coisas que são possíveis realizar com o KIF.

# Data
29/05/2018

# Dados do Apresentador
Nome: João Pedro Henriques Parreiras e Souza
Onde trabalha: Concrete
Email: joao.souza@concrete.com.br
Username no iOSDevBR:
Redes sociais:
https://www.linkedin.com/in/joão-souza-2547a272/

**Comment by gabrieloliva** [comment]
@joaopedrok Evento aberto no meetup! https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/251023554/

**Comment by gabrieloliva** [comment]
@joaopedrok Muito obrigado pela palestra! Você poderia abrir um PR atualizando o `past-talks.md` com os links da sua talk?

**Comment by joaopedrok** [comment]
@gabrieloliva claro... até o final do dia eu faço isso.
