### ISSUE TITLE
Utilizando Redux em suas aplicações com ReSwift

### ISSUE THREAD

**Issue by vinsalmont** [CocoaheadsBH/talks#18]
# Título da talk
Utilizando Redux em suas aplicações com ReSwift

# Descrição da talk
Introdução ao Redux no Swift utilizando o ReSwift, exemplificando suas aplicações através de um projeto de exemplo.

# Data
29/05/2018

# Dados do Apresentador
Nome: Vinícius Salmont
Onde trabalha: Concrete
Email: vinicius.salmont@concrete.com.br
Username no iOSDevBR: Vinícius Salmont
Redes sociais: 
LinkedIn: https://www.linkedin.com/in/vin%C3%ADcius-salmont-bb9a5a79/

Projeto de teste: https://github.com/vinsalmont/ReSwift-example

**Comment by gabrieloliva** [comment]
@vinsalmont Evento aberto no meetup! https://www.meetup.com/pt-BR/CocoaHeads-Talks-BH/events/251023554/

**Comment by gabrieloliva** [comment]
@vinsalmont Muito obrigado pela palestra! Você poderia abrir um PR atualizando o `past-talks.md` com os links da sua talk?
